version: "3.6"
services:
  node:
    build: .
    user: "node"
    entrypoint: docker-entrypoint-watch.sh
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./www:/home/node/app
      - ./out:/home/node/app/out
    ports:
      - "3000:3000"